// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[...path].tsx";
import * as $1 from "./routes/api/note.ts";
import * as $2 from "./routes/index.tsx";
import * as $$0 from "./islands/CreateNoteForm.tsx";
import * as $$1 from "./islands/CurrentPageURL.tsx";
import * as $$2 from "./islands/Notepad.tsx";

const manifest = {
  routes: {
    "./routes/[...path].tsx": $0,
    "./routes/api/note.ts": $1,
    "./routes/index.tsx": $2,
  },
  islands: {
    "./islands/CreateNoteForm.tsx": $$0,
    "./islands/CurrentPageURL.tsx": $$1,
    "./islands/Notepad.tsx": $$2,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
